id: 08aeeccf94a74e66bbdf604210ad06ae
title: Toh_676-The_Dharani_Essence_of_Immeasurable_Longevity_and_Wisdom-v1
type: translation
source_metadata:
  creationtool: InterText
  creationtoolversion: '1.0'
  datatype: PlainText
  segtype: block
  adminlang: en-us
  srclang: bo
  o-tmf: XML aligned text
  eft-text-id: UT22084-091-074
  eft-text-version: 1.0.5 2021
